/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as DescargasRouteImport } from './routes/descargas'
import { Route as SeguimientoRouteImport } from './routes/seguimiento'
import { Route as ApiPublicNotifyReservationRouteImport } from './routes/api/public/notify-reservation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargasRoute = DescargasRouteImport.update({
  id: '/descargas',
  path: '/descargas',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyReservationRoute =
  ApiPublicNotifyReservationRouteImport.update({
    id: '/api/public/notify-reservation',
    path: '/api/public/notify-reservation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conductor': typeof ConductorRoute
  '/descargas': typeof DescargasRoute
  '/seguimiento': typeof SeguimientoRoute
  '/api/public/notify-reservation': typeof ApiPublicNotifyReservationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conductor': typeof ConductorRoute
  '/descargas': typeof DescargasRoute
  '/seguimiento': typeof SeguimientoRoute
  '/api/public/notify-reservation': typeof ApiPublicNotifyReservationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conductor': typeof ConductorRoute
  '/descargas': typeof DescargasRoute
  '/seguimiento': typeof SeguimientoRoute
  '/api/public/notify-reservation': typeof ApiPublicNotifyReservationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conductor'
    | '/descargas'
    | '/seguimiento'
    | '/api/public/notify-reservation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conductor'
    | '/descargas'
    | '/seguimiento'
    | '/api/public/notify-reservation'
  id:
    | '__root__'
    | '/'
    | '/conductor'
    | '/descargas'
    | '/seguimiento'
    | '/api/public/notify-reservation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConductorRoute: typeof ConductorRoute
  DescargasRoute: typeof DescargasRoute
  SeguimientoRoute: typeof SeguimientoRoute
  ApiPublicNotifyReservationRoute: typeof ApiPublicNotifyReservationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargas': {
      id: '/descargas'
      path: '/descargas'
      fullPath: '/descargas'
      preLoaderRoute: typeof DescargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento': {
      id: '/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-reservation': {
      id: '/api/public/notify-reservation'
      path: '/api/public/notify-reservation'
      fullPath: '/api/public/notify-reservation'
      preLoaderRoute: typeof ApiPublicNotifyReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConductorRoute: ConductorRoute,
  DescargasRoute: DescargasRoute,
  SeguimientoRoute: SeguimientoRoute,
  ApiPublicNotifyReservationRoute: ApiPublicNotifyReservationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}